# Generated by Django 2.1.3 on 2019-03-20 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
